services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=seriedadedb
    volumes:
      - seriedadedb_pg_data:/var/lib/postgresql/data

volumes:
  seriedadedb_pg_data:
